### ISSUE TITLE
If the same category exists in both Buy and Sell offers, the one in Buy offers will be un-expandable

### ISSUE THREAD

**Issue by Slickytail** [SR-Textbook-Service/src_textbook#21]

**Comment by askdfjlas** [comment]
Oh nice, I think this is a little oversight on giving elements IDs on my part, will fix tonight

**Comment by Slickytail** [comment]
You don't need to fix it. I'm currently overhauling the entire UI and I inadvertently fixed the issue.

**Comment by askdfjlas** [comment]
Oh damn nice, I'll get back to the ripper stuff then. was it the IDs though?

**Comment by Slickytail** [comment]
It was not the IDs. The issue was the the call was something like `expand_category("mathematics")` without regard for the fact that there might be two mathematics categories.
